apiVersion : apps/v1
kind: Deployment
metadata:
  name: "cluster-2ced"
spec:
  replicas: 2
  selector:
    matchLabels:
      app: "cluster-2ced"
  template:
    metadata:
      labels:
        app: "cluster-2ced"
    spec:
      containers:
        - name: "cluster-2ced"
          image: "gkkjkkk.azurecr.io/cluster"
          ports:
          - containerPort: 8080