apiVersion: v1
kind: Service
metadata:
    name: "cluster-2ced"
    labels:
        app: "cluster-2ced"
spec:
    type: LoadBalancer
    ports:
    - port: 8080
      targetPort: 8080
      protocol: TCP
      name: http
    selector:
        app: "cluster-2ced"